name: AWS Terraform Provision
on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    name: "Terraform Plan"
    runs-on: mdn-self-hosted-runner
    if: github.actor == github.repository_owner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::177701659471:role/github-to-aws-terraform-provisioner
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan # Saves the plan to a file

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

  terraform-deploy:
    name: "Terraform Apply"
    needs: terraform-plan # WAIT for the plan to finish
    runs-on: ubuntu-latest
    if: github.actor == github.repository_owner
    environment: staging # Manual Approval Gate
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::177701659471:role/github-to-aws-terraform-provisioner
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Deploy to AWS
        run: terraform apply -auto-approve tfplan # Uses the EXACT plan from before

  terraform-destroy:
    name: "Terraform destroy"
    needs: terraform-deploy # WAIT for the plan to finish
    runs-on: ubuntu-latest
    if: github.actor == github.repository_owner
    environment: staging # Manual Approval Gate
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::177701659471:role/github-to-aws-terraform-provisioner
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform destroy
        run: terraform destroy -auto-approve
 